name: Deploy to ECR

on:
  push:  
    tags:
      - demo-viewer-v*

jobs:

  publish_docker:
    name: Build and Publish Docker
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get tag name 
      id: tagName
      uses: dawidd6/action-get-tag@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ github.event.repository.name }}
        IMAGE_TAG: ${{ steps.tagName.outputs.tag }}
        DOCKERFILE_PATH: examples/video_stream/docker/viewer-dockerfile
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE_PATH .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG